### ISSUE TITLE
Spec doesn't specify r value of trimpots rp1-rp3

### ISSUE THREAD

**Issue by ogg1e** [dekkit/RGB-to-Component-Transcoder#5]
Just wondering what R value to use for the 3 trimpots?  100 ohm?

**Comment by dekkit** [comment]
they aren't necessary, but 100 or 150 ohm trimpot should do it .   

Note: The default resistors in are  75 ohm (for each colour) and is a typical convention used for video circuits, so it really depends on how much extra attenuation you need for your particular use case (ie colours are dull because your using an old arcade board and you want to use the trimpot to help give it a boost).  

If you are not sure what you need, just omit the trimpots and stay with the fixed value 75 ohm resistor.
